use crate::{config::Provider, history::TranslationUsage};
use futures_util::StreamExt;
use reqwest::{
    header::{HeaderName, HeaderValue},
    Client, StatusCode,
};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use tauri::{AppHandle, Emitter, Manager, State};
use tokio::sync::{oneshot, Mutex};

#[cfg(not(any(target_os = "android", target_os = "ios")))]
use tauri_plugin_notification::NotificationExt;

/// Registry of in-flight translation requests that can be cancelled.
/// Keyed by a monotonically incrementing `request_id` generated by the frontend.
pub type CancellationRegistry = Arc<Mutex<HashMap<u64, oneshot::Sender<()>>>>;

/// A single delta chunk from the streaming response.
#[derive(Debug, Deserialize)]
struct StreamChoice {
    delta: StreamDelta,
}

#[derive(Debug, Deserialize)]
struct StreamDelta {
    content: Option<String>,
}

#[derive(Debug, Deserialize)]
struct StreamChunk {
    #[serde(default)]
    choices: Vec<StreamChoice>,
    usage: Option<TranslationUsage>,
}

#[derive(Clone, Serialize)]
struct TranslationChunkPayload {
    request_id: u64,
    content: String,
}

#[derive(Clone, Serialize)]
struct TranslationDonePayload {
    request_id: u64,
}

#[derive(Clone, Serialize)]
struct TranslationErrorPayload {
    request_id: u64,
    message: String,
}

#[derive(Clone, Serialize)]
struct TranslationRetryPayload {
    request_id: u64,
    attempt: u8,
}

#[derive(Clone, Serialize)]
struct TranslationUsagePayload {
    request_id: u64,
    usage: TranslationUsage,
}

#[derive(Debug, PartialEq, Eq)]
enum SseLine {
    Ignore,
    Done,
    Update(StreamUpdate),
}

#[derive(Debug, PartialEq, Eq)]
struct StreamUpdate {
    contents: Vec<String>,
    usage: Option<TranslationUsage>,
}

#[derive(Clone, Copy)]
struct RetryConfig {
    max_retries: u8,
    base_retry_ms: u64,
}

impl Default for RetryConfig {
    fn default() -> Self {
        Self {
            max_retries: 3,
            base_retry_ms: 200,
        }
    }
}

struct TranslationRequest<'a> {
    text: &'a str,
    source_lang: &'a str,
    target_lang: &'a str,
    api_key: &'a str,
    model: &'a str,
    api_base_url: &'a str,
    provider: &'a Provider,
}

struct StreamCompletion {
    translated_text: String,
    cancelled: bool,
    usage: Option<TranslationUsage>,
}

trait TranslationEventSink {
    fn emit_chunk(&mut self, request_id: u64, content: String);
    fn emit_done(&mut self, request_id: u64);
    fn emit_error(&mut self, request_id: u64, message: String);
    fn emit_retry(&mut self, request_id: u64, attempt: u8);
    fn emit_usage(&mut self, _request_id: u64, _usage: TranslationUsage) {}
    fn notify_background_success(&mut self) {}
    fn notify_background_error(&mut self, _message: &str) {}
    fn notify_background_retry(&mut self, _attempt: u8) {}
}

struct TauriEventSink<'a> {
    app: &'a AppHandle,
}

impl TranslationEventSink for TauriEventSink<'_> {
    fn emit_chunk(&mut self, request_id: u64, content: String) {
        let _ = self.app.emit(
            "translation-chunk",
            TranslationChunkPayload {
                request_id,
                content,
            },
        );
    }

    fn emit_done(&mut self, request_id: u64) {
        let _ = self
            .app
            .emit("translation-done", TranslationDonePayload { request_id });
    }

    fn emit_error(&mut self, request_id: u64, message: String) {
        let _ = self.app.emit(
            "translation-error",
            TranslationErrorPayload {
                request_id,
                message,
            },
        );
    }

    fn emit_retry(&mut self, request_id: u64, attempt: u8) {
        let _ = self.app.emit(
            "translation-retry",
            TranslationRetryPayload {
                request_id,
                attempt,
            },
        );
    }

    fn emit_usage(&mut self, request_id: u64, usage: TranslationUsage) {
        let _ = self.app.emit(
            "translation-usage",
            TranslationUsagePayload { request_id, usage },
        );
    }

    fn notify_background_success(&mut self) {
        notify_translation_background(
            self.app,
            "Translation ready",
            "The latest translation is ready. Left-click the tray icon to reopen Aura.",
        );
    }

    fn notify_background_error(&mut self, message: &str) {
        notify_translation_background(
            self.app,
            "Translation failed",
            format!(
                "The last request failed: {}",
                summarize_notification_message(message)
            ),
        );
    }

    fn notify_background_retry(&mut self, attempt: u8) {
        notify_translation_background(
            self.app,
            "Translation retrying",
            format!(
                "Aura is retrying the last request in the background (attempt {}).",
                attempt
            ),
        );
    }
}

#[cfg(not(any(target_os = "android", target_os = "ios")))]
fn notify_translation_background(app: &AppHandle, title: &str, body: impl Into<String>) {
    let window_hidden = app
        .get_webview_window(crate::TRANSLATION_WINDOW_LABEL)
        .and_then(|window| window.is_visible().ok())
        .map(|visible| !visible)
        .unwrap_or(true);

    if !window_hidden {
        return;
    }

    let _ = app
        .notification()
        .builder()
        .title(title)
        .body(body.into())
        .show();
}

#[cfg(any(target_os = "android", target_os = "ios"))]
fn notify_translation_background(_app: &AppHandle, _title: &str, _body: impl Into<String>) {}

fn summarize_notification_message(message: &str) -> String {
    let collapsed = message.split_whitespace().collect::<Vec<_>>().join(" ");
    let char_count = collapsed.chars().count();
    if char_count <= 120 {
        return collapsed;
    }

    collapsed.chars().take(117).collect::<String>() + "..."
}

/// Translate text using a streaming chat completions endpoint.
/// Supports any OpenAI-compatible provider (DeepSeek, OpenRouter, Ollama).
///
/// Emits request-scoped `translation-chunk` events to the frontend for each token.
/// Emits request-scoped `translation-done` when the stream is complete (including on cancellation).
/// Emits request-scoped `translation-error` on failure.
#[tauri::command]
pub async fn translate_text(
    app: AppHandle,
    client: State<'_, Client>,
    history: State<'_, crate::HistoryState>,
    registry: State<'_, CancellationRegistry>,
    text: String,
    source_lang: String,
    target_lang: String,
    api_key: String,
    model: String,
    request_id: u64,
    api_base_url: String,
    provider: Provider,
) -> Result<(), String> {
    // Set up cancellation channel for this request
    let (cancel_tx, cancel_rx) = oneshot::channel::<()>();
    {
        let mut reg = registry.lock().await;
        reg.insert(request_id, cancel_tx);
    }

    let request = TranslationRequest {
        text: &text,
        source_lang: &source_lang,
        target_lang: &target_lang,
        api_key: &api_key,
        model: &model,
        api_base_url: &api_base_url,
        provider: &provider,
    };

    let mut sink = TauriEventSink { app: &app };
    let result = translate_stream_with_sink(
        &mut sink,
        &client,
        cancel_rx,
        request,
        request_id,
        RetryConfig::default(),
    )
    .await;

    // Clean up registry entry regardless of outcome
    {
        let mut reg = registry.lock().await;
        reg.remove(&request_id);
    }

    match &result {
        Ok(completion) if !completion.cancelled && !completion.translated_text.is_empty() => {
            if let Err(err) = record_history_success(
                history.inner().clone(),
                &text,
                &completion.translated_text,
                &source_lang,
                &target_lang,
                &provider,
                &model,
                completion.usage.clone(),
            )
            .await
            {
                eprintln!("Failed to record translation history: {}", err);
            }
        }
        Err(message) => {
            if let Err(err) = record_history_error(
                history.inner().clone(),
                &text,
                message,
                &source_lang,
                &target_lang,
                &provider,
                &model,
            )
            .await
            {
                eprintln!("Failed to record translation history: {}", err);
            }
        }
        _ => {}
    }

    result.map(|_| ())
}

/// Internal streaming logic, separated to cleanly handle cancellation cleanup.
async fn translate_stream_with_sink<S: TranslationEventSink>(
    sink: &mut S,
    client: &Client,
    mut cancel_rx: oneshot::Receiver<()>,
    request: TranslationRequest<'_>,
    request_id: u64,
    retry_config: RetryConfig,
) -> Result<StreamCompletion, String> {
    let body = build_chat_request_body(&request);
    let url = build_chat_completions_url(request.api_base_url);
    let mut received_output = false;
    let mut translated_text = String::new();
    let mut usage: Option<TranslationUsage> = None;

    let response = {
        let mut attempt = 0;
        loop {
            let headers = match provider_headers(request.provider, request.api_key) {
                Ok(headers) => headers,
                Err(err) => {
                    sink.emit_error(request_id, err.clone());
                    sink.notify_background_error(&err);
                    return Err(err);
                }
            };

            let mut http_request = client.post(&url).header("Content-Type", "application/json");
            for (name, value) in headers {
                http_request = http_request.header(name, value);
            }
            http_request = http_request.json(&body);

            // Check cancellation while waiting for the HTTP response
            let outcome = tokio::select! {
                _ = &mut cancel_rx => {
                    sink.emit_done(request_id);
                    return Ok(StreamCompletion {
                        translated_text,
                        cancelled: true,
                        usage,
                    });
                }
                result = http_request.send() => result,
            };

            let failure = match outcome {
                Ok(resp) => {
                    if resp.status().is_success() {
                        break Ok(resp);
                    }
                    let status = resp.status();
                    let error_body = resp.text().await.unwrap_or_default();
                    let msg = format!("API error ({}): {}", status, error_body);
                    if !is_retryable_status(status) {
                        sink.emit_error(request_id, msg.clone());
                        sink.notify_background_error(&msg);
                        return Err(msg);
                    }
                    msg
                }
                Err(err) => {
                    let msg = format!("Network error: {}", err);
                    if !is_retryable_transport_error(&err) {
                        sink.emit_error(request_id, msg.clone());
                        sink.notify_background_error(&msg);
                        return Err(msg);
                    }
                    msg
                }
            };

            if attempt >= retry_config.max_retries {
                sink.emit_error(request_id, failure.clone());
                sink.notify_background_error(&failure);
                break Err(failure);
            }

            let delay = retry_config.base_retry_ms * 3u64.pow(attempt as u32);
            sink.emit_retry(request_id, attempt + 1);
            sink.notify_background_retry(attempt + 1);

            // Check cancellation during the backoff delay
            tokio::select! {
                _ = &mut cancel_rx => {
                    sink.emit_done(request_id);
                    return Ok(StreamCompletion {
                        translated_text,
                        cancelled: true,
                        usage,
                    });
                }
                _ = tokio::time::sleep(tokio::time::Duration::from_millis(delay)) => {}
            }

            attempt += 1;
        }
    }?;

    let mut stream = response.bytes_stream();
    let mut buffer = String::new();

    loop {
        tokio::select! {
            // Check for cancellation signal
            _ = &mut cancel_rx => {
                sink.emit_done(request_id);
                return Ok(StreamCompletion {
                    translated_text,
                    cancelled: true,
                    usage,
                });
            }
            // Process next SSE chunk
            chunk_opt = stream.next() => {
                match chunk_opt {
                    Some(chunk_result) => {
                        let chunk = match chunk_result {
                            Ok(chunk) => chunk,
                            Err(err) => {
                                let msg = format!("Stream error: {}", err);
                                sink.emit_error(request_id, msg.clone());
                                sink.notify_background_error(&msg);
                                return Err(msg);
                            }
                        };

                        // Normalize line endings: proxies may send \r\n
                        let text = String::from_utf8_lossy(&chunk).replace('\r', "");
                        buffer.push_str(&text);

                        // SSE format: each line starts with "data: "
                        while let Some(pos) = buffer.find('\n') {
                            let line = buffer[..pos].trim().to_string();
                            buffer = buffer[pos + 1..].to_string();

                            if line.is_empty() {
                                continue;
                            }

                            match parse_sse_line(&line) {
                                Ok(SseLine::Ignore) => {}
                                Ok(SseLine::Done) => {
                                    sink.emit_done(request_id);
                                    if received_output {
                                        sink.notify_background_success();
                                    }
                                    return Ok(StreamCompletion {
                                        translated_text,
                                        cancelled: false,
                                        usage,
                                    });
                                }
                                Ok(SseLine::Update(update)) => {
                                    if let Some(next_usage) = update.usage {
                                        usage = Some(next_usage.clone());
                                        sink.emit_usage(request_id, next_usage);
                                    }

                                    for content in update.contents {
                                        received_output = true;
                                        translated_text.push_str(&content);
                                        sink.emit_chunk(request_id, content);
                                    }
                                }
                                Err(msg) => {
                                    sink.emit_error(request_id, msg.clone());
                                    sink.notify_background_error(&msg);
                                    return Err(msg);
                                }
                            }
                        }
                    }
                    None => {
                        // Stream ended without [DONE] sentinel
                        sink.emit_done(request_id);
                        if received_output {
                            sink.notify_background_success();
                        }
                        return Ok(StreamCompletion {
                            translated_text,
                            cancelled: false,
                            usage,
                        });
                    }
                }
            }
        }
    }
}

async fn record_history_success(
    history_state: crate::HistoryState,
    source_text: &str,
    translated_text: &str,
    source_lang: &str,
    target_lang: &str,
    provider: &Provider,
    model: &str,
    usage: Option<TranslationUsage>,
) -> Result<(), String> {
    history_state.lock().await.record_success(
        source_text,
        translated_text,
        source_lang,
        target_lang,
        provider,
        model,
        usage,
    )
}

async fn record_history_error(
    history_state: crate::HistoryState,
    source_text: &str,
    error_message: &str,
    source_lang: &str,
    target_lang: &str,
    provider: &Provider,
    model: &str,
) -> Result<(), String> {
    history_state.lock().await.record_error(
        source_text,
        error_message,
        source_lang,
        target_lang,
        provider,
        model,
        None,
    )
}

fn build_chat_request_body(request: &TranslationRequest<'_>) -> serde_json::Value {
    let system_prompt = build_system_prompt(request.source_lang, request.target_lang);
    let mut body = serde_json::json!({
        "model": request.model,
        "messages": [
            { "role": "system", "content": system_prompt },
            { "role": "user", "content": request.text }
        ],
        "temperature": 0.3,
        "stream": true
    });

    if !matches!(request.provider, Provider::Ollama) {
        body["stream_options"] = serde_json::json!({
            "include_usage": true
        });
    }

    body
}

fn build_system_prompt(source_lang: &str, target_lang: &str) -> String {
    if source_lang == "auto" {
        format!(
            "You are a professional translator. Auto-detect the source language of the following text \
             and translate it into {}. Output ONLY the translated text, nothing else. \
             Do not add any explanations, notes, or quotation marks.",
            target_lang
        )
    } else {
        format!(
            "You are a professional translator. Translate the following text from {} to {}. \
             Output ONLY the translated text, nothing else. \
             Do not add any explanations, notes, or quotation marks.",
            source_lang, target_lang
        )
    }
}

fn build_chat_completions_url(api_base_url: &str) -> String {
    format!("{}/chat/completions", api_base_url.trim_end_matches('/'))
}

fn provider_headers(
    provider: &Provider,
    api_key: &str,
) -> Result<Vec<(HeaderName, HeaderValue)>, String> {
    match provider {
        Provider::Ollama => Ok(Vec::new()),
        Provider::DeepSeek => Ok(vec![authorization_header(api_key)?]),
        Provider::OpenRouter => Ok(vec![
            authorization_header(api_key)?,
            (
                HeaderName::from_static("http-referer"),
                HeaderValue::from_static("https://github.com/MapleAllen/Aura-Translation"),
            ),
            (
                HeaderName::from_static("x-title"),
                HeaderValue::from_static("Aura Translation"),
            ),
        ]),
    }
}

fn authorization_header(api_key: &str) -> Result<(HeaderName, HeaderValue), String> {
    let value = HeaderValue::from_str(&format!("Bearer {}", api_key))
        .map_err(|err| format!("Invalid API key header: {}", err))?;
    Ok((HeaderName::from_static("authorization"), value))
}

fn is_retryable_status(status: StatusCode) -> bool {
    status.is_server_error()
}

fn is_retryable_transport_error(err: &reqwest::Error) -> bool {
    err.is_connect() || err.is_timeout()
}

fn parse_sse_line(line: &str) -> Result<SseLine, String> {
    if line.is_empty() {
        return Ok(SseLine::Ignore);
    }

    if line == "data: [DONE]" {
        return Ok(SseLine::Done);
    }

    let Some(json_str) = line.strip_prefix("data: ") else {
        return Ok(SseLine::Ignore);
    };

    let parsed = serde_json::from_str::<StreamChunk>(json_str)
        .map_err(|e| format!("Malformed SSE data: {}", e))?;

    let contents = parsed
        .choices
        .into_iter()
        .filter_map(|choice| choice.delta.content)
        .filter(|content| !content.is_empty())
        .collect();

    Ok(SseLine::Update(StreamUpdate {
        contents,
        usage: parsed.usage,
    }))
}

/// Cancel an in-flight translation request by its ID.
/// Sends the cancellation signal; the stream loop will emit translation-done
/// with whatever partial text has already been sent.
#[tauri::command]
pub async fn cancel_translate(
    registry: State<'_, CancellationRegistry>,
    request_id: u64,
) -> Result<(), String> {
    let mut reg = registry.lock().await;
    if let Some(sender) = reg.remove(&request_id) {
        // Ignoring send error — receiver may have already been dropped
        // if the translation completed naturally before the cancel arrived.
        let _ = sender.send(());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::VecDeque;
    use std::sync::{Arc, Mutex as StdMutex};
    use std::time::Duration;
    use tokio::sync::oneshot;
    use wiremock::{
        matchers::{header, method, path},
        Mock, MockServer, Request, Respond, ResponseTemplate,
    };

    #[derive(Debug, Clone, PartialEq, Eq)]
    enum CapturedEvent {
        Chunk(String),
        Done,
        Error(String),
        Retry(u8),
        Usage(TranslationUsage),
    }

    #[derive(Default)]
    struct TestSink {
        events: Vec<CapturedEvent>,
    }

    impl TranslationEventSink for TestSink {
        fn emit_chunk(&mut self, _request_id: u64, content: String) {
            self.events.push(CapturedEvent::Chunk(content));
        }

        fn emit_done(&mut self, _request_id: u64) {
            self.events.push(CapturedEvent::Done);
        }

        fn emit_error(&mut self, _request_id: u64, message: String) {
            self.events.push(CapturedEvent::Error(message));
        }

        fn emit_retry(&mut self, _request_id: u64, attempt: u8) {
            self.events.push(CapturedEvent::Retry(attempt));
        }

        fn emit_usage(&mut self, _request_id: u64, usage: TranslationUsage) {
            self.events.push(CapturedEvent::Usage(usage));
        }
    }

    #[derive(Clone)]
    struct SequenceResponder {
        responses: Arc<StdMutex<VecDeque<ResponseTemplate>>>,
    }

    impl SequenceResponder {
        fn new(responses: Vec<ResponseTemplate>) -> Self {
            Self {
                responses: Arc::new(StdMutex::new(responses.into())),
            }
        }
    }

    impl Respond for SequenceResponder {
        fn respond(&self, _request: &Request) -> ResponseTemplate {
            let mut responses = self.responses.lock().unwrap();
            if responses.len() > 1 {
                responses.pop_front().unwrap()
            } else {
                responses.front().cloned().unwrap()
            }
        }
    }

    fn sse_body(content: &str) -> String {
        format!(
            "data: {{\"choices\":[{{\"delta\":{{\"content\":\"{}\"}}}}]}}\n\ndata: [DONE]\n",
            content
        )
    }

    fn test_request<'a>(
        api_base_url: &'a str,
        provider: &'a Provider,
        api_key: &'a str,
    ) -> TranslationRequest<'a> {
        TranslationRequest {
            text: "hello",
            source_lang: "English",
            target_lang: "Chinese",
            api_key,
            model: "test-model",
            api_base_url,
            provider,
        }
    }

    async fn run_request(
        sink: &mut TestSink,
        api_base_url: &str,
        provider: &Provider,
        api_key: &str,
        retry_config: RetryConfig,
    ) -> Result<StreamCompletion, String> {
        let (_cancel_tx, cancel_rx) = oneshot::channel();
        translate_stream_with_sink(
            sink,
            &Client::new(),
            cancel_rx,
            test_request(api_base_url, provider, api_key),
            42,
            retry_config,
        )
        .await
    }

    #[test]
    fn parses_valid_sse_chunk() {
        let line = r#"data: {"choices":[{"delta":{"content":"hello"}}]}"#;
        let parsed = parse_sse_line(line).expect("valid SSE should parse");
        assert_eq!(
            parsed,
            SseLine::Update(StreamUpdate {
                contents: vec!["hello".to_string()],
                usage: None,
            })
        );
    }

    #[test]
    fn parses_done_sentinel() {
        let parsed = parse_sse_line("data: [DONE]").expect("DONE should parse");
        assert_eq!(parsed, SseLine::Done);
    }

    #[test]
    fn ignores_empty_content_and_non_data_lines() {
        let empty = r#"data: {"choices":[{"delta":{"content":""}}]}"#;
        assert_eq!(
            parse_sse_line(empty).expect("empty content JSON is valid"),
            SseLine::Update(StreamUpdate {
                contents: Vec::new(),
                usage: None,
            })
        );
        assert_eq!(
            parse_sse_line(": keep-alive").expect("comments are ignored"),
            SseLine::Ignore
        );
    }

    #[test]
    fn parses_usage_only_chunk() {
        let line = r#"data: {"choices":[],"usage":{"prompt_tokens":11,"completion_tokens":7,"total_tokens":18}}"#;
        let parsed = parse_sse_line(line).expect("usage-only SSE should parse");
        assert_eq!(
            parsed,
            SseLine::Update(StreamUpdate {
                contents: Vec::new(),
                usage: Some(TranslationUsage {
                    prompt_tokens: 11,
                    completion_tokens: 7,
                    total_tokens: 18,
                }),
            })
        );
    }

    #[test]
    fn rejects_malformed_data_json() {
        let err = parse_sse_line(r#"data: {"choices":["#).expect_err("malformed JSON should fail");
        assert!(err.starts_with("Malformed SSE data:"));
    }

    #[test]
    fn parses_crlf_normalized_line() {
        let raw = "data: {\"choices\":[{\"delta\":{\"content\":\"ok\"}}]}\r\n";
        let line = raw.replace('\r', "");
        let line = line.trim();
        assert_eq!(
            parse_sse_line(line).expect("CRLF-normalized line should parse"),
            SseLine::Update(StreamUpdate {
                contents: vec!["ok".to_string()],
                usage: None,
            })
        );
    }

    #[test]
    fn trims_trailing_slash_from_base_url() {
        assert_eq!(
            build_chat_completions_url("http://localhost:11434/"),
            "http://localhost:11434/chat/completions"
        );
    }

    #[test]
    fn openrouter_headers_include_referer_and_title() {
        let headers = provider_headers(&Provider::OpenRouter, "sk-openrouter").unwrap();
        assert_eq!(headers.len(), 3);
        assert_eq!(headers[0].0, HeaderName::from_static("authorization"));
        assert_eq!(headers[1].0, HeaderName::from_static("http-referer"));
        assert_eq!(headers[2].0, HeaderName::from_static("x-title"));
    }

    #[tokio::test]
    async fn deepseek_requests_use_bearer_auth() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/chat/completions"))
            .and(header("authorization", "Bearer sk-deepseek"))
            .respond_with(ResponseTemplate::new(200).set_body_string(sse_body("你好")))
            .mount(&server)
            .await;

        let mut sink = TestSink::default();
        run_request(
            &mut sink,
            &server.uri(),
            &Provider::DeepSeek,
            "sk-deepseek",
            RetryConfig {
                max_retries: 0,
                base_retry_ms: 1,
            },
        )
        .await
        .expect("deepseek request should succeed");

        assert_eq!(
            sink.events,
            vec![CapturedEvent::Chunk("你好".into()), CapturedEvent::Done]
        );
    }

    #[tokio::test]
    async fn openrouter_requests_include_required_headers() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/chat/completions"))
            .and(header("authorization", "Bearer sk-openrouter"))
            .and(header(
                "http-referer",
                "https://github.com/MapleAllen/Aura-Translation",
            ))
            .and(header("x-title", "Aura Translation"))
            .respond_with(ResponseTemplate::new(200).set_body_string(sse_body("hola")))
            .mount(&server)
            .await;

        let mut sink = TestSink::default();
        run_request(
            &mut sink,
            &server.uri(),
            &Provider::OpenRouter,
            "sk-openrouter",
            RetryConfig {
                max_retries: 0,
                base_retry_ms: 1,
            },
        )
        .await
        .expect("openrouter request should succeed");

        assert_eq!(
            sink.events,
            vec![CapturedEvent::Chunk("hola".into()), CapturedEvent::Done]
        );
    }

    #[tokio::test]
    async fn ollama_requests_do_not_send_auth_headers() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .and(path("/chat/completions"))
            .respond_with(ResponseTemplate::new(200).set_body_string(sse_body("bonjour")))
            .mount(&server)
            .await;

        let mut sink = TestSink::default();
        run_request(
            &mut sink,
            &server.uri(),
            &Provider::Ollama,
            "",
            RetryConfig {
                max_retries: 0,
                base_retry_ms: 1,
            },
        )
        .await
        .expect("ollama request should succeed");

        let requests = server.received_requests().await.unwrap();
        assert_eq!(requests.len(), 1);
        assert!(!requests[0].headers.contains_key("authorization"));
        assert_eq!(
            sink.events,
            vec![CapturedEvent::Chunk("bonjour".into()), CapturedEvent::Done]
        );
    }

    #[tokio::test]
    async fn client_errors_do_not_retry() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .respond_with(ResponseTemplate::new(401).set_body_string("bad key"))
            .mount(&server)
            .await;

        let mut sink = TestSink::default();
        let result = run_request(
            &mut sink,
            &server.uri(),
            &Provider::DeepSeek,
            "sk-bad",
            RetryConfig {
                max_retries: 3,
                base_retry_ms: 1,
            },
        )
        .await;

        assert!(result.is_err());
        let requests = server.received_requests().await.unwrap();
        assert_eq!(requests.len(), 1);
        assert_eq!(sink.events.len(), 1);
        assert!(matches!(sink.events[0], CapturedEvent::Error(_)));
        assert!(!sink
            .events
            .iter()
            .any(|event| matches!(event, CapturedEvent::Retry(_))));
    }

    #[tokio::test]
    async fn server_errors_retry_before_success() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .respond_with(SequenceResponder::new(vec![
                ResponseTemplate::new(500).set_body_string("temporary"),
                ResponseTemplate::new(502).set_body_string("temporary"),
                ResponseTemplate::new(200).set_body_string(sse_body("重试成功")),
            ]))
            .mount(&server)
            .await;

        let mut sink = TestSink::default();
        run_request(
            &mut sink,
            &server.uri(),
            &Provider::DeepSeek,
            "sk-ok",
            RetryConfig {
                max_retries: 3,
                base_retry_ms: 1,
            },
        )
        .await
        .expect("request should eventually succeed");

        let requests = server.received_requests().await.unwrap();
        assert_eq!(requests.len(), 3);
        assert_eq!(
            sink.events,
            vec![
                CapturedEvent::Retry(1),
                CapturedEvent::Retry(2),
                CapturedEvent::Chunk("重试成功".into()),
                CapturedEvent::Done
            ]
        );
    }

    #[tokio::test]
    async fn cancellation_emits_done_without_error() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .respond_with(
                ResponseTemplate::new(200)
                    .set_delay(Duration::from_millis(250))
                    .set_body_string(sse_body("should-not-arrive")),
            )
            .mount(&server)
            .await;

        let mut sink = TestSink::default();
        let (cancel_tx, cancel_rx) = oneshot::channel();
        let cancel_task = tokio::spawn(async move {
            tokio::time::sleep(Duration::from_millis(25)).await;
            let _ = cancel_tx.send(());
        });

        let result = translate_stream_with_sink(
            &mut sink,
            &Client::new(),
            cancel_rx,
            test_request(&server.uri(), &Provider::DeepSeek, "sk-cancel"),
            7,
            RetryConfig {
                max_retries: 0,
                base_retry_ms: 1,
            },
        )
        .await;

        cancel_task.await.unwrap();
        assert!(result.is_ok());
        assert_eq!(sink.events, vec![CapturedEvent::Done]);
    }

    #[tokio::test]
    async fn malformed_sse_surfaces_error() {
        let server = MockServer::start().await;
        Mock::given(method("POST"))
            .respond_with(ResponseTemplate::new(200).set_body_string("data: {\"choices\":[\n"))
            .mount(&server)
            .await;

        let mut sink = TestSink::default();
        let result = run_request(
            &mut sink,
            &server.uri(),
            &Provider::DeepSeek,
            "sk-bad-stream",
            RetryConfig {
                max_retries: 0,
                base_retry_ms: 1,
            },
        )
        .await;

        assert!(result.is_err());
        assert_eq!(sink.events.len(), 1);
        assert!(matches!(sink.events[0], CapturedEvent::Error(_)));
    }
}
