use crate::config::Provider;
use futures_util::StreamExt;
use reqwest::Client;
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use std::sync::Arc;
use tauri::{AppHandle, Emitter, State};
use tokio::sync::{oneshot, Mutex};

/// Registry of in-flight translation requests that can be cancelled.
/// Keyed by a monotonically incrementing `request_id` generated by the frontend.
pub type CancellationRegistry = Arc<Mutex<HashMap<u64, oneshot::Sender<()>>>>;

/// A single delta chunk from the streaming response.
#[derive(Debug, Deserialize)]
struct StreamChoice {
    delta: StreamDelta,
}

#[derive(Debug, Deserialize)]
struct StreamDelta {
    content: Option<String>,
}

#[derive(Debug, Deserialize)]
struct StreamChunk {
    choices: Vec<StreamChoice>,
}

#[derive(Clone, Serialize)]
struct TranslationChunkPayload {
    request_id: u64,
    content: String,
}

#[derive(Clone, Serialize)]
struct TranslationDonePayload {
    request_id: u64,
}

#[derive(Clone, Serialize)]
struct TranslationErrorPayload {
    request_id: u64,
    message: String,
}

#[derive(Clone, Serialize)]
struct TranslationRetryPayload {
    request_id: u64,
    attempt: u8,
}

#[derive(Debug, PartialEq, Eq)]
enum SseLine {
    Ignore,
    Done,
    Chunks(Vec<String>),
}

/// Translate text using a streaming chat completions endpoint.
/// Supports any OpenAI-compatible provider (DeepSeek, OpenRouter, Ollama).
///
/// Emits request-scoped `translation-chunk` events to the frontend for each token.
/// Emits request-scoped `translation-done` when the stream is complete (including on cancellation).
/// Emits request-scoped `translation-error` on failure.
#[tauri::command]
pub async fn translate_text(
    app: AppHandle,
    client: State<'_, Client>,
    registry: State<'_, CancellationRegistry>,
    text: String,
    source_lang: String,
    target_lang: String,
    api_key: String,
    model: String,
    request_id: u64,
    api_base_url: String,
    provider: Provider,
) -> Result<(), String> {
    // Set up cancellation channel for this request
    let (cancel_tx, cancel_rx) = oneshot::channel::<()>();
    {
        let mut reg = registry.lock().await;
        reg.insert(request_id, cancel_tx);
    }

    let result = translate_stream(
        &app,
        &client,
        cancel_rx,
        &text,
        &source_lang,
        &target_lang,
        &api_key,
        &model,
        &api_base_url,
        &provider,
        request_id,
    )
    .await;

    // Clean up registry entry regardless of outcome
    {
        let mut reg = registry.lock().await;
        reg.remove(&request_id);
    }

    result
}

/// Internal streaming logic, separated to cleanly handle cancellation cleanup.
async fn translate_stream(
    app: &AppHandle,
    client: &Client,
    mut cancel_rx: oneshot::Receiver<()>,
    text: &str,
    source_lang: &str,
    target_lang: &str,
    api_key: &str,
    model: &str,
    api_base_url: &str,
    provider: &Provider,
    request_id: u64,
) -> Result<(), String> {
    let system_prompt = if source_lang == "auto" {
        format!(
            "You are a professional translator. Auto-detect the source language of the following text \
             and translate it into {}. Output ONLY the translated text, nothing else. \
             Do not add any explanations, notes, or quotation marks.",
            target_lang
        )
    } else {
        format!(
            "You are a professional translator. Translate the following text from {} to {}. \
             Output ONLY the translated text, nothing else. \
             Do not add any explanations, notes, or quotation marks.",
            source_lang, target_lang
        )
    };

    let body = serde_json::json!({
        "model": model,
        "messages": [
            { "role": "system", "content": system_prompt },
            { "role": "user", "content": text }
        ],
        "temperature": 0.3,
        "stream": true
    });

    let url = format!("{}/chat/completions", api_base_url.trim_end_matches('/'));
    let max_retries = 3u8; // Initial request + up to 3 retries.
    let base_retry_ms = 200u64;

    let response = {
        #[allow(unused_assignments)]
        let mut last_err = String::new();
        let mut attempt = 0;
        loop {
            let mut request = client
                .post(&url)
                .header("Content-Type", "application/json")
                .json(&body);

            match provider {
                Provider::Ollama => {}
                Provider::OpenRouter => {
                    request = request
                        .header("Authorization", format!("Bearer {}", api_key))
                        .header(
                            "HTTP-Referer",
                            "https://github.com/MapleAllen/Aura-Translation",
                        )
                        .header("X-Title", "Aura Translation");
                }
                Provider::DeepSeek => {
                    request = request.header("Authorization", format!("Bearer {}", api_key));
                }
            }

            // Check cancellation while waiting for the HTTP response
            let outcome = tokio::select! {
                _ = &mut cancel_rx => {
                    emit_done(app, request_id);
                    return Ok(());
                }
                result = request.send() => result,
            };

            match outcome {
                Ok(resp) => {
                    if resp.status().is_success() {
                        break Ok(resp);
                    }
                    let status = resp.status();
                    let error_body = resp.text().await.unwrap_or_default();
                    let msg = format!("API error ({}): {}", status, error_body);
                    if status.is_client_error() {
                        emit_error(app, request_id, &msg);
                        return Err(msg);
                    }
                    last_err = msg;
                }
                Err(e) => {
                    let msg = format!("Network error: {}", e);
                    if !e.is_connect() && !e.is_timeout() {
                        emit_error(app, request_id, &msg);
                        return Err(msg);
                    }
                    last_err = msg;
                }
            }

            if attempt >= max_retries {
                emit_error(app, request_id, &last_err);
                break Err(last_err);
            }
            let delay = base_retry_ms * 3u64.pow(attempt as u32);
            emit_retry(app, request_id, attempt + 1);

            // Check cancellation during the backoff delay
            tokio::select! {
                _ = &mut cancel_rx => {
                    emit_done(app, request_id);
                    return Ok(());
                }
                _ = tokio::time::sleep(tokio::time::Duration::from_millis(delay)) => {}
            }

            attempt += 1;
        }
    }?;

    let mut stream = response.bytes_stream();
    let mut buffer = String::new();

    loop {
        tokio::select! {
            // Check for cancellation signal
            _ = &mut cancel_rx => {
                // Cancelled by user — emit translation-done to preserve partial text
                emit_done(app, request_id);
                return Ok(());
            }
            // Process next SSE chunk
            chunk_opt = stream.next() => {
                match chunk_opt {
                    Some(chunk_result) => {
                        let chunk = chunk_result.map_err(|e| {
                            let msg = format!("Stream error: {}", e);
                            emit_error(app, request_id, &msg);
                            msg
                        })?;

                        // Normalize line endings: proxies may send \r\n
                        let text = String::from_utf8_lossy(&chunk).replace('\r', "");
                        buffer.push_str(&text);

                        // SSE format: each line starts with "data: "
                        while let Some(pos) = buffer.find('\n') {
                            let line = buffer[..pos].trim().to_string();
                            buffer = buffer[pos + 1..].to_string();

                            if line.is_empty() {
                                continue;
                            }

                            match parse_sse_line(&line) {
                                Ok(SseLine::Ignore) => {}
                                Ok(SseLine::Done) => {
                                    emit_done(app, request_id);
                                    return Ok(());
                                }
                                Ok(SseLine::Chunks(contents)) => {
                                    for content in contents {
                                        emit_chunk(app, request_id, content);
                                    }
                                }
                                Err(msg) => {
                                    emit_error(app, request_id, &msg);
                                    return Err(msg);
                                }
                            }
                        }
                    }
                    None => {
                        // Stream ended without [DONE] sentinel
                        emit_done(app, request_id);
                        return Ok(());
                    }
                }
            }
        }
    }
}

fn parse_sse_line(line: &str) -> Result<SseLine, String> {
    if line.is_empty() {
        return Ok(SseLine::Ignore);
    }

    if line == "data: [DONE]" {
        return Ok(SseLine::Done);
    }

    let Some(json_str) = line.strip_prefix("data: ") else {
        return Ok(SseLine::Ignore);
    };

    let parsed = serde_json::from_str::<StreamChunk>(json_str)
        .map_err(|e| format!("Malformed SSE data: {}", e))?;

    let contents = parsed
        .choices
        .into_iter()
        .filter_map(|choice| choice.delta.content)
        .filter(|content| !content.is_empty())
        .collect();

    Ok(SseLine::Chunks(contents))
}

fn emit_chunk(app: &AppHandle, request_id: u64, content: String) {
    let _ = app.emit(
        "translation-chunk",
        TranslationChunkPayload {
            request_id,
            content,
        },
    );
}

fn emit_done(app: &AppHandle, request_id: u64) {
    let _ = app.emit("translation-done", TranslationDonePayload { request_id });
}

fn emit_error(app: &AppHandle, request_id: u64, message: &str) {
    let _ = app.emit(
        "translation-error",
        TranslationErrorPayload {
            request_id,
            message: message.to_string(),
        },
    );
}

fn emit_retry(app: &AppHandle, request_id: u64, attempt: u8) {
    let _ = app.emit(
        "translation-retry",
        TranslationRetryPayload {
            request_id,
            attempt,
        },
    );
}

/// Cancel an in-flight translation request by its ID.
/// Sends the cancellation signal; the stream loop will emit translation-done
/// with whatever partial text has already been sent.
#[tauri::command]
pub async fn cancel_translate(
    registry: State<'_, CancellationRegistry>,
    request_id: u64,
) -> Result<(), String> {
    let mut reg = registry.lock().await;
    if let Some(sender) = reg.remove(&request_id) {
        // Ignoring send error — receiver may have already been dropped
        // if the translation completed naturally before the cancel arrived.
        let _ = sender.send(());
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parses_valid_sse_chunk() {
        let line = r#"data: {"choices":[{"delta":{"content":"hello"}}]}"#;
        let parsed = parse_sse_line(line).expect("valid SSE should parse");
        assert_eq!(parsed, SseLine::Chunks(vec!["hello".to_string()]));
    }

    #[test]
    fn parses_done_sentinel() {
        let parsed = parse_sse_line("data: [DONE]").expect("DONE should parse");
        assert_eq!(parsed, SseLine::Done);
    }

    #[test]
    fn ignores_empty_content_and_non_data_lines() {
        let empty = r#"data: {"choices":[{"delta":{"content":""}}]}"#;
        assert_eq!(
            parse_sse_line(empty).expect("empty content JSON is valid"),
            SseLine::Chunks(Vec::new())
        );
        assert_eq!(
            parse_sse_line(": keep-alive").expect("comments are ignored"),
            SseLine::Ignore
        );
    }

    #[test]
    fn rejects_malformed_data_json() {
        let err = parse_sse_line(r#"data: {"choices":["#).expect_err("malformed JSON should fail");
        assert!(err.starts_with("Malformed SSE data:"));
    }

    #[test]
    fn parses_crlf_normalized_line() {
        let raw = "data: {\"choices\":[{\"delta\":{\"content\":\"ok\"}}]}\r\n";
        let line = raw.replace('\r', "");
        let line = line.trim();
        assert_eq!(
            parse_sse_line(line).expect("CRLF-normalized line should parse"),
            SseLine::Chunks(vec!["ok".to_string()])
        );
    }
}
