use futures_util::StreamExt;
use reqwest::Client;
use serde::Deserialize;
use std::collections::HashMap;
use std::sync::Arc;
use tauri::{AppHandle, Emitter, State};
use tokio::sync::{oneshot, Mutex};

/// Registry of in-flight translation requests that can be cancelled.
/// Keyed by a monotonically incrementing `request_id` generated by the frontend.
pub type CancellationRegistry = Arc<Mutex<HashMap<u64, oneshot::Sender<()>>>>;

/// A single delta chunk from the streaming response.
#[derive(Debug, Deserialize)]
struct StreamChoice {
    delta: StreamDelta,
}

#[derive(Debug, Deserialize)]
struct StreamDelta {
    content: Option<String>,
}

#[derive(Debug, Deserialize)]
struct StreamChunk {
    choices: Vec<StreamChoice>,
}

/// Translate text using a streaming chat completions endpoint.
/// Supports any OpenAI-compatible provider (DeepSeek, OpenRouter, Ollama).
///
/// Emits `translation-chunk` events to the frontend for each token.
/// Emits `translation-done` when the stream is complete (including on cancellation).
/// Emits `translation-error` on failure.
#[tauri::command]
pub async fn translate_text(
    app: AppHandle,
    client: State<'_, Client>,
    registry: State<'_, CancellationRegistry>,
    text: String,
    source_lang: String,
    target_lang: String,
    api_key: String,
    model: String,
    request_id: u64,
    api_base_url: String,
    provider: String,
) -> Result<(), String> {
    // Set up cancellation channel for this request
    let (cancel_tx, cancel_rx) = oneshot::channel::<()>();
    {
        let mut reg = registry.lock().await;
        reg.insert(request_id, cancel_tx);
    }

    let result = translate_stream(
        &app,
        &client,
        cancel_rx,
        &text,
        &source_lang,
        &target_lang,
        &api_key,
        &model,
        &api_base_url,
        &provider,
    )
    .await;

    // Clean up registry entry regardless of outcome
    {
        let mut reg = registry.lock().await;
        reg.remove(&request_id);
    }

    result
}

/// Internal streaming logic, separated to cleanly handle cancellation cleanup.
async fn translate_stream(
    app: &AppHandle,
    client: &Client,
    mut cancel_rx: oneshot::Receiver<()>,
    text: &str,
    source_lang: &str,
    target_lang: &str,
    api_key: &str,
    model: &str,
    api_base_url: &str,
    provider: &str,
) -> Result<(), String> {
    let system_prompt = if source_lang == "auto" {
        format!(
            "You are a professional translator. Auto-detect the source language of the following text \
             and translate it into {}. Output ONLY the translated text, nothing else. \
             Do not add any explanations, notes, or quotation marks.",
            target_lang
        )
    } else {
        format!(
            "You are a professional translator. Translate the following text from {} to {}. \
             Output ONLY the translated text, nothing else. \
             Do not add any explanations, notes, or quotation marks.",
            source_lang, target_lang
        )
    };

    let body = serde_json::json!({
        "model": model,
        "messages": [
            { "role": "system", "content": system_prompt },
            { "role": "user", "content": text }
        ],
        "temperature": 0.3,
        "stream": true
    });

    let url = format!("{}/chat/completions", api_base_url.trim_end_matches('/'));
    let max_retries = 3u8;
    let base_retry_ms = 200u64;

    let response = {
        let mut last_err = String::new();
        let mut attempt = 0;
        loop {
            let mut request = client
                .post(&url)
                .header("Content-Type", "application/json")
                .json(&body);

            match provider {
                "ollama" => {}
                "openrouter" => {
                    request = request
                        .header("Authorization", format!("Bearer {}", api_key))
                        .header("HTTP-Referer", "https://github.com/MapleAllen/Aura-Translation")
                        .header("X-Title", "Aura Translation");
                }
                _ => {
                    request = request.header("Authorization", format!("Bearer {}", api_key));
                }
            }

            match request.send().await {
                Ok(resp) => {
                    if resp.status().is_success() {
                        break Ok(resp);
                    }
                    let status = resp.status();
                    let error_body = resp.text().await.unwrap_or_default();
                    let msg = format!("API error ({}): {}", status, error_body);
                    if status.is_client_error() {
                        let _ = app.emit("translation-error", &msg);
                        return Err(msg);
                    }
                    last_err = msg;
                }
                Err(e) => {
                    let msg = format!("Network error: {}", e);
                    if !e.is_connect() && !e.is_timeout() {
                        let _ = app.emit("translation-error", &msg);
                        return Err(msg);
                    }
                    last_err = msg;
                }
            }

            if attempt >= max_retries {
                break Err(last_err);
            }
            let delay = base_retry_ms * 3u64.pow(attempt as u32);
            let _ = app.emit("translation-retry", serde_json::json!({ "attempt": attempt + 1 }));
            tokio::time::sleep(tokio::time::Duration::from_millis(delay)).await;
            attempt += 1;
        }
    }?;

    let mut stream = response.bytes_stream();
    let mut buffer = String::new();

    loop {
        tokio::select! {
            // Check for cancellation signal
            _ = &mut cancel_rx => {
                // Cancelled by user — emit translation-done to preserve partial text
                let _ = app.emit("translation-done", ());
                return Ok(());
            }
            // Process next SSE chunk
            chunk_opt = stream.next() => {
                match chunk_opt {
                    Some(chunk_result) => {
                        let chunk = chunk_result.map_err(|e| {
                            let msg = format!("Stream error: {}", e);
                            let _ = app.emit("translation-error", &msg);
                            msg
                        })?;

                        // Normalize line endings: proxies may send \r\n
                        let text = String::from_utf8_lossy(&chunk).replace('\r', "");
                        buffer.push_str(&text);

                        // SSE format: each line starts with "data: "
                        while let Some(pos) = buffer.find('\n') {
                            let line = buffer[..pos].trim().to_string();
                            buffer = buffer[pos + 1..].to_string();

                            if line.is_empty() {
                                continue;
                            }

                            if line == "data: [DONE]" {
                                let _ = app.emit("translation-done", ());
                                return Ok(());
                            }

                            if let Some(json_str) = line.strip_prefix("data: ") {
                                if let Ok(parsed) = serde_json::from_str::<StreamChunk>(json_str) {
                                    for choice in &parsed.choices {
                                        if let Some(content) = &choice.delta.content {
                                            if !content.is_empty() {
                                                let _ = app.emit("translation-chunk", content.clone());
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    None => {
                        // Stream ended without [DONE] sentinel
                        let _ = app.emit("translation-done", ());
                        return Ok(());
                    }
                }
            }
        }
    }
}

/// Cancel an in-flight translation request by its ID.
/// Sends the cancellation signal; the stream loop will emit translation-done
/// with whatever partial text has already been sent.
#[tauri::command]
pub async fn cancel_translate(
    registry: State<'_, CancellationRegistry>,
    request_id: u64,
) -> Result<(), String> {
    let mut reg = registry.lock().await;
    if let Some(sender) = reg.remove(&request_id) {
        // Ignoring send error — receiver may have already been dropped
        // if the translation completed naturally before the cancel arrived.
        let _ = sender.send(());
    }
    Ok(())
}
